SYS:
  EXP_NAME: 'test2'
  GPUS: (0,1,2,3)
  WORKERS: 8
  PIN_MEMORY: True
  LOCAL_RANK: ''


TRAIN:
  RESUME: ''
  START_EPOCH: 1
  END_EPOCH: 1
  PRINT_FREQ: 1
  BATCH_SIZE: 16
  BATCH_SIZE_VAL: 4
  SEED: 1007
  CUDNN:
    BENCHMARK: True
    DETERMINISTIC: False
    ENABLED: True
  OPT: 
    NAME: 'SGD'
    LR: 0.02
    NBB_LR: 0.06
    WD: 0.0001
    MOMENTUM: 0.9

MODEL:
  NAME: 'ctx48'
  BB_PRETRAINED: ''
  LOSS: ''
  FREEZE_BN: ''
  NBB_KEYWORDS: []


DATA:
  SET: 'cityscapes'
  ROOT: 'cityscapes/'
  NUM_CLASSES: 19
  TRAIN_SPLIT: 'train'
  VAL_SPLIT: 'val'
  TEST_SPLIT: 'test'
  SHUFFLE: False
  DROP_LAST: True
  AUG:
    R_SCALE: [0.5,2]
    CROP_SIZE: [768, 1536] # [1024,2048]
